
attack = {
    "damage": {
        "branch": "attack",
        "min": 0,
        "max": 6000,
        "unit": "",
        "name": "Damage",
        "description": "Damage each projectile deals to enemies",
    },
    "attack_speed": {
        "branch": "attack",
        "min": 0,
        "max": 99,
        "unit": "",
        "name": "Attack Speed",
        "description": "Speed projectiles are fired from your tower",
    },
    "crit_chance": {
        "branch": "attack",
        "min": 0,
        "max": 79,
        "unit": "%",
        "name": "Critical Chance",
        "description": "Chance to deal a critical hit",
    },
    "crit_factor": {
        "branch": "attack",
        "min": 0,
        "max": 150,
        "unit": "x",
        "name": "Critical Factor",
        "description": "Multiplier applied to damage on a critical hit",
    },
    "range": {
        "branch": "attack",
        "min": 0,
        "max": 79,
        "unit": "m",
        "name": "Range",
        "description": "Maximum distance at which the attack can hit",
    },
    "dmg_per_meter": {
        "branch": "attack",
        "min": 0,
        "max": 200,
        "unit": "% / m",
        "name": "Damage per Meter",
        "description": "Amount of damage dealt per meter of distance",
    },
    "multishot_chance": {
        "branch": "attack",
        "min": 0,
        "max": 99,
        "unit": "%",
        "name": "Multishot Chance",
        "description": "Chance to fire multiple projectiles when firing",
    },
    "multishot_targets": {
        "branch": "attack",
        "min": 0,
        "max": 7,
        "unit": "x",
        "name": "Multishot Targets",
        "description": "Number of projectiles shot when multishot activates (if enough enemies in range)",
    },
    "rapid_fire_chance": {
        "branch": "attack",
        "min": 0,
        "max": 85,
        "unit": "%",
        "name": "Rapid Fire Chance",
        "description": "Chance to fire 4x as fast as normal for a duration",
    },
    "rapid_fire_duration": {
        "branch": "attack",
        "min": 0,
        "max": 99,
        "unit": "sec",
        "name": "Rapid Fire Duration",
        "description": "Duration of rapid fire effect when activated",
    },
    "bounce_shot_chance": {
        "branch": "attack",
        "min": 0,
        "max": 85,
        "unit": "%",
        "name": "Bounce Shot Chance",
        "description": "Chance for projectile to bounce to another enemy",
    },
    "bounce_shot_targets": {
        "branch": "attack",
        "min": 0,
        "max": 7,
        "unit": "",
        "name": "Bounce Shot Targets",
        "description": "Number of time a projectile can bounce from enemy to enemy",
    },
    "bounce_shot_range": {
        "branch": "attack",
        "min": 0,
        "max": 60,
        "unit": "m",
        "name": "Bounce Shot Range",
        "description": "Maximum distance at which a bouncing shot can hit a target",
    },
    "super_crit_chance": {
        "branch": "attack",
        "min": 0,
        "max": 100,
        "unit": "%",
        "name": "Super Crit Chance",
        "description": "Chance to deal a super critical hit if critical hit succeeds",
    },
    "super_crit_mult": {
        "branch": "attack",
        "min": 0,
        "max": 120,
        "unit": "x",
        "name": "Super Crit Multiplier",
        "description": "Multiplier applied to damage on a super critical hit",
    },
    "rend_armor_chance": {
        "branch": "attack",
        "min": 0,
        "max": 299,
        "unit": "%",
        "name": "Rend Armor Chance",
        "description": "Chance on enemy hit of permanently increasing the damage that enemy takes from projectiles",
    },
    "rend_armor_mult": {
        "branch": "attack",
        "min": 0,
        "max": 299,
        "unit": "%",
        "name": "Rend Armor Multiplier",
        "description": "Amount of additional damage that the enemy takes",
    }  
}

