defence = {
    "health": {
        "branch": "defence",
        "min": 0,
        "max": 6000,
        "unit": "",
        "name": "Health",
        "description": "Increases the base amount of health you have.",
    },
    "health_regen": {
        "branch": "defence",
        "min": 0,
        "max": 6000,
        "unit": "/sec",
        "name": "Health Regen",
        "description": "Increases the amount of health you regenerate per second.",
    },
    "defence_perc": {
        "branch": "defence",
        "min": 0,
        "max": 99,
        "unit": "%",
        "name": "Defence %",
        "description": "Decreases the amount of damage you take.",
    },
    "defence_abs": {
        "branch": "defence",
        "min": 0,
        "max": 5000,
        "unit": "",
        "name": "Defence absolute",
        "description": "Decreases the amount of damage before defence absolute is applied.",
    },
    "thorn_dmg": {
        "branch": "defence",
        "min": 0,
        "max": 99,
        "unit": "%",
        "name": "Thorn Damage",
        "description": "Reflects a percentage of the damage you take back to the enemy.",
    },
    "lifesteal": {
        "branch": "defence",
        "min": 0,
        "max": 80,
        "unit": "%",
        "name": "Lifesteal",
        "description": "Heals you for a percentage of the damage you deal.",
    },
    "knockback_chance": {
        "branch": "defence",
        "min": 0,
        "max": 80,
        "unit": "%",
        "name": "Knockback Chance",
        "description": "Chance to knockback enemies when you hit them.",
    },
    "knockback_force": {
        "branch": "defence",
        "min": 0,
        "max": 40,
        "unit": "",
        "name": "Knockback Force",
        "description": "Increases the force of the knockback.",
    },
    "orb_speed": {
        "branch": "defence",
        "min": 0,
        "max": 38,
        "unit": "",
        "name": "Orb Speed",
        "description": "Increases the speed of orbs.",
    },
    "orbs": {
        "branch": "defence",
        "min": 0,
        "max": 4,
        "unit": "",
        "name": "Orbs",
        "description": "Increases the number of orbs you have.",
    },
    "shockwave_size": {
        "branch": "defence",
        "min": 0,
        "max": 35,
        "unit": "",
        "name": "Shockwave Size",
        "description": "Increases the size of the shockwave.",
    },
    "shockwave_freq": {
        "branch": "defence",
        "min": 0,
        "max": 40,
        "unit": "sec",
        "name": "Shockwave Frequency",
        "description": "Increases the frequency of the shockwave.",
    },
    "landmine_chance": {
        "branch": "defence",
        "min": 0,
        "max": 50,
        "unit": "%",
        "name": "Landmine Chance",
        "description": "Chance to spawn a landmine at enemy death.",
    },
    "landmine_dmg": {
        "branch": "defence",
        "min": 0,
        "max": 200,
        "unit": "%",
        "name": "Landmine Damage",
        "description": "Percentage of tower damage dealt by landmine.",
    },
    "landmine_radius": {
        "branch": "defence",
        "min": 0,
        "max": 50,
        "unit": "",
        "name": "Landmine Radius",
        "description": "Increases the radius of the landmine.",
    },
    "death_defy": {
        "branch": "defence",
        "min": 0,
        "max": 75,
        "unit": "%",
        "name": "Death Defy",
        "description": "Chance to survive a fatal hit.",
    },
    "wall_health": {
        "branch": "defence",
        "min": 0,
        "max": 1800,
        "unit": "%",
        "name": "Wall Health",
        "description": "Maximum health of the wall based on percentage of tower health.",
    }, 
    "wall_rebuild": {
        "branch": "defence",
        "min": 0,
        "max": 300,
        "unit": "sec",
        "name": "Wall Rebuild",
        "description": "Time it takes to rebuild the wall.",
    },
}

