utility = {
    "cash_bonus": {
        "branch": "utility",
        "min": 0,
        "max": 149,
        "unit": "x",
        "name": "Cash Bonus",
        "description": "Cash earned from all sources (includes wave bonus)",
    },
    "cash_per_wave": {
        "branch": "utility",
        "min": 0,
        "max": 149,
        "unit": "",
        "name": "Cash per Wave",
        "description": "Cash you get at the end of each wave.",
    },
    "coin_per_kill": {
        "branch": "utility",
        "min": 0,
        "max": 149,
        "unit": "x",
        "name": "Coin per Kill",
        "description": "Coins you get for each enemy killed.",
    },
    "coins_per_wave": {
        "branch": "utility",
        "min": 0,
        "max": 149,
        "unit": "",
        "name": "Coins per Wave",
        "description": "Coins you get at the end of each wave.",
    },
    "free_attack_upgrade": {
        "branch": "utility",
        "min": 0,
        "max": 99,
        "unit": "%",
        "name": "Free Attack Upgrade",
        "description": "Chance to get a free attack upgrade at the end of each wave",
    },
    "free_defence_upgrade": {
        "branch": "utility",
        "min": 0,
        "max": 99,
        "unit": "%",
        "name": "Free Defence Upgrade",
        "description": "Chance to get a free defence upgrade at the end of each wave",
    },
    "free_utility_upgrade": {
        "branch": "utility",
        "min": 0,
        "max": 99,
        "unit": "%",
        "name": "Free Utility Upgrade",
        "description": "Chance to get a free utility upgrade at the end of each wave",
    },
    "interest_per_wave": {
        "branch": "utility",
        "min": 0,
        "max": 99,
        "unit": "%",
        "name": "Interest per Wave",
        "description": "Interest you get at the end of each wave.",
    },
    "recovery_amount": {
        "branch": "utility",
        "min": 0,
        "max": 300,
        "unit": "%",
        "name": "Recovery Amount",
        "description": "Percentage of max health each package recovers.",
    },
    "max_recovery": {
        "branch": "utility",
        "min": 0,
        "max": 500,
        "unit": "x",
        "name": "Max Recovery",
        "description": "How much beyond max health you can recover.",
    },
    "package_chance": {
        "branch": "utility",
        "min": 0,
        "max": 60,
        "unit": "%",
        "name": "Package Chance",
        "description": "Chance to receive a package at the end of each wave.",
    },
    "enemy_attack_lvl_skip": {
        "branch": "utility",
        "min": 0,
        "max": 699,
        "unit": "%",
        "name": "Enemy Attack Level Skip",
        "description": "Chance of skipping enemy attack level after wave",
    },
    "enemy_health_lvl_skip": {
        "branch": "utility",
        "min": 0,
        "max": 699,
        "unit": "%",
        "name": "Enemy Health Level Skip",
        "description": "Chance of skipping enemy health level after wave",
    }
}


